### ISSUE TITLE
About the compressed file error 

### ISSUE THREAD

**Issue by wangwwww** [souvikdc9/aryan-emphemeris.net#1]
May I ask, I downloaded the resource file you uploaded, but there was an error when unzipping it, could you please upload the resource file again? Looking forward to using the code you uploaded, thank you！
This is the resource file：https://github.com/souvikdc9/aryan-emphemeris.net

**Comment by ghost** [comment]
This is not an issue with zip file. Zip files are created by GitHub when downloading the repository. Use `git clone` command to clone the repository.
